### ISSUE TITLE
CI build failing for release/core_1.0rc/1.1

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/SpidrPlugin#31]
The CI build for [release/core_1.0rc/1.1](https://github.com/ManiVaultStudio/SpidrPlugin/tree/release/core_1.0rc/1.1) is [failing](https://github.com/ManiVaultStudio/SpidrPlugin/actions/runs/8122548470/job/22202099207):

```
ERROR: Missing binary: hdps-core/1.0rc@lkeb/stable:3423a283afef2479f49bc36d4027e47b2269f8a4
hdps-core/1.0rc@lkeb/stable: WARN: Can't find a 'hdps-core/1.0rc@lkeb/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=10, os=Linux
- Options: fPIC=True, macos_bundle=False, shared=True, qt:charts=False, qt:commercial=False, qt:datavis3d=False, qt:imageformats=True, qt:networkauth=False, qt:opengl=desktop, qt:openssl=True, qt:positioning=True, qt:qt5compat=True, qt:target=desktop, qt:virtualkeyboard=False, qt:webchannel=True, qt:webengine=True, zlib:fPIC=True, zlib:shared=False
- Dependencies: qt/6.3.2@lkeb/stable, zlib/1.3
- Requirements: qt/6.Y.Z, zlib/1.Y.Z
- Package ID: 3423a283afef2479f49bc36d4027e47b2269f8a4
```
, despite the changes below:
```
matrix:
    include:
      - name: Windows-msvc2019
        os: windows-2019
        compiler: msvc-2019
        build-cversion: 16
        build-runtime: MD
        build-config: Release
      - name: Linux_gcc11
        os: ubuntu-22.04
        build-cc: gcc
        build-cxx: g++
        build-compiler: gcc
        build-cversion: 11
        build-config: Release
        build-os: Linux
        build-libcxx: libstdc++
      - name: Macos_xcode13.4
        os: macos-12
        build-compiler: apple-clang
        build-cversion: 13
        build-config: Release
        build-os: Macos
        build-xcode-version: 13.4
        build-libcxx: libc++
```
